CREATE TABLE Sportler(S_Id NUMBER NOT NULL PRIMARY KEY, S_Vorname varchar2(30), 
    S_Nachname varchar2(30), S_Geburtsdatum DATE, L_Id NUMBER NOT NULL, 
    SP_Id NUMBER NOT NULL, S_Siege NUMBER NOT NULL, S_Niederlagen NUMBER NOT NULL, 
    S_GesamtWettkämpfe NUMBER NOT NULL);
CREATE TABLE Land(L_Id NUMBER NOT NULL PRIMARY KEY, L_Name varchar2(30) NOT NULL);
CREATE TABLE Sport(SP_Id NUMBER NOT NULL PRIMARY KEY, SP_Name varchar2(30) NOT NULL,
    SA_Id NUMBER NOT NULL);
CREATE TABLE SportArt(SA_Id NUMBER NOT NULL PRIMARY KEY, SA_Bezeichnung varchar2(30), 
    SA_Team CHAR(1) CONSTRAINT SA_Team_check CHECK(SA_TEAM IN ('1','0')));
CREATE TABLE TeamsportArt(SA_Id NUMBER NOT NULL PRIMARY KEY, T_Id NUMBER NOT NULL);
CREATE TABLE EinzelsportArt(SA_Id NUMBER NOT NULL PRIMARY KEY);
CREATE TABLE Wettbewerb(W_Id NUMBER NOT NULL PRIMARY KEY, W_Name varchar2(30), 
    W_Preisgeld NUMBER, W_Datum DATE); 
CREATE TABLE Einzel_Wettbewerb(W_Id NUMBER NOT NULL PRIMARY KEY,
    Anzahl_Sportler NUMBER NOT NULL);
CREATE TABLE Team_Wettbewerb(W_Id NUMBER NOT NULL PRIMARY KEY, T_Id NUMBER NOT NULL, 
    Anzahl_Teams NUMBER NOT NULL);
CREATE TABLE Sportler_Team(S_Id NUMBER NOT NULL PRIMARY KEY, T_Id NUMBER NOT NULL, 
    Beitrittsdatum DATE);
CREATE TABLE Wettkampf(WK_Id NUMBER NOT NULL PRIMARY KEY, WK_Name varchar2(50) NOT NULL, 
    W_Id NUMBER NOT NULL);
CREATE TABLE Einzelwettkampf(WK_Id NUMBER NOT NULL PRIMARY KEY, S_Id_1 NUMBER NOT NULL, 
    S_Id_2 NUMBER NOT NULL, Datum DATE, Sieger NUMBER NOT NULL);
CREATE TABLE Teamwettkampf(WK_Id NUmber NOT NULL PRIMARY KEY, T_Id_1 NUMBER NOT NULL, 
    T_Id_2 NUMBER NOT NULL, DATUM DATE, Sieger NUMBER NOT NULL);
CREATE TABLE Team(T_Id NUMBER NOT NULL PRIMARY KEY,T_Name varchar2(50) NOT NULL, 
    SP_Id NUMBER NOT NULL, L_Id NUMBER NOT NULL, Gründungsjahr NUMBER NOT NULL,
    Anzahl_Sportler NUMBER NOT NULL);
ALTER TABLE Sportler ADD CONSTRAINT Sportler_Land_FK 
    FOREIGN KEY(L_Id) REFERENCES Land(L_Id) ON DELETE SET NULL;
ALTER TABLE Sportler ADD CONSTRAINT Sportler_Sport_FK 
    FOREIGN KEY(SP_Id) REFERENCES Sport(SP_Id) ON DELETE SET NULL;
ALTER TABLE Sport ADD CONSTRAINT Sport_SportArt_FK 
    FOREIGN KEY(SA_Id) REFERENCES SportArt(SA_Id) ON DELETE SET NULL;
ALTER TABLE TeamsportArt ADD CONSTRAINT TeamsportArt_SportArt_FK 
    FOREIGN KEY(SA_Id) REFERENCES SportArt(SA_Id) ON DELETE CASCADE;
ALTER TABLE TeamsportArt ADD CONSTRAINT TeamsportArt_Team_FK 
    FOREIGN KEY(T_Id) REFERENCES Team(T_Id) ON DELETE CASCADE;
ALTER TABLE Team_Wettbewerb ADD CONSTRAINT Team_Wettbewerb_Wettbewerb_FK 
    FOREIGN KEY(W_Id) REFERENCES Wettbewerb(W_Id) ON DELETE CASCADE;
ALTER TABLE Team_Wettbewerb ADD CONSTRAINT Team_Wettbewerb_Team_FK 
    FOREIGN KEY(T_Id) REFERENCES Team(T_Id) ON DELETE CASCADE;
ALTER TABLE Einzel_Wettbewerb ADD CONSTRAINT Einzel_Wettbewerb_Wettbewerb_FK 
    FOREIGN KEY(W_Id) REFERENCES Wettbewerb(W_Id) ON DELETE CASCADE;
ALTER TABLE Einzelwettkampf ADD CONSTRAINT Einzelwettkampf_Sportler_1_FK 
    FOREIGN KEY(S_Id_1) REFERENCES Sportler(S_Id) ON DELETE CASCADE;
ALTER TABLE Einzelwettkampf ADD CONSTRAINT Einzelwettkampf_Sportler_2_FK 
    FOREIGN KEY(S_Id_2) REFERENCES Sportler(S_Id) ON DELETE CASCADE;
ALTER TABLE Einzelwettkampf ADD CONSTRAINT Einzelwettkampf_Sportler_Sieger_FK 
    FOREIGN KEY(Sieger) REFERENCES Sportler(S_Id);
ALTER TABLE Einzelwettkampf ADD CONSTRAINT Einzelwettkampf_Wettkampf_FK 
    FOREIGN KEY(WK_Id) REFERENCES Wettkampf(WK_Id) ON DELETE SET NULL;
ALTER TABLE Teamwettkampf ADD CONSTRAINT Teamwettkampf_Wettkampf_FK 
    FOREIGN KEY(WK_Id) REFERENCES Wettkampf(WK_Id) ON DELETE SET NULL;
ALTER TABLE Teamwettkampf ADD CONSTRAINT Teamwettkampf_Team_1_FK 
    FOREIGN KEY(T_Id_1) REFERENCES Team(T_Id);
ALTER TABLE Teamwettkampf ADD CONSTRAINT Teamwettkampf_Team2_FK 
    FOREIGN KEY(T_Id_2) REFERENCES Team(T_Id);
ALTER TABLE EinzelsportArt ADD CONSTRAINT EinzelsportArt_SportArt_FK 
    FOREIGN KEY(SA_Id) REFERENCES SportArt(SA_Id) ON DELETE CASCADE;
ALTER TABLE Sportler_Team ADD CONSTRAINT Sportler_Team_Sportler_FK 
    FOREIGN KEY(S_Id) REFERENCES Sportler(S_Id) ON DELETE CASCADE;
ALTER TABLE Sportler_Team ADD CONSTRAINT Sportler_Team_Team_FK 
    FOREIGN KEY(T_Id) REFERENCES Team(T_Id) ON DELETE CASCADE;
ALTER TABLE Team ADD CONSTRAINT Team_Land_FK 
    FOREIGN KEY(L_Id) REFERENCES Land(L_Id);
ALTER TABLE Team ADD CONSTRAINT Team_Sport_FK 
    FOREIGN KEY (SP_Id) REFERENCES Sport(SP_Id);
